Add tests for keypair generation and JWT creation
astarte-platform/astartectl_test_suite pull request #24
Opened 2024-11-26 13:45 UTC by Jusuf95

Tests for astartectl Utility Commands for Keypair and JWT Generation

This pull request adds tests for astartectl utility commands, specifically for keypair generation and JWT creation across different scopes. The tests verify that the commands execute successfully and produce valid outputs.

Changes and Tests Added:

1. Keypair Generation:

- test_utils_gen_keypair verifies that the keypair is successfully generated for the specified realm.

1. JWT Generation:

- test_utils_gen_jwt_* tests generating JWTs for various scopes:
- All realms
- Realm management
- Appengine
- Pairing
- Housekeeping
- Flow
- Channels

2024-11-26 14:03 UTC, osmanhadzic approved these changes

2024-11-26 14:59 UTC, Annopaolo requested changes

2024-11-26 14:59 UTC, Annopaolo commented on tests/utils/test_utils_generate.py
> +    assert len(sample_data_result.stdout) > 0
The output JWT should contain only specific claims (see [here](https://docs.astarte-platform.org/astarte/latest/070-auth.html#token-claims-and-formats)). You can use [pyjwt](https://pyjwt.readthedocs.io/en/stable/) or [python-jose](https://github.com/mpdavis/python-jose) (or any other library) to check that the correct claims were generated

2024-11-27 09:35 UTC, osmanhadzic approved these changes

2024-12-02 09:10 UTC, ackermannW approved these changes

2024-12-02 13:57 UTC, Annopaolo approved these changes
Code is good! 
It would be great to add, in another PR, tests for the `-c` option. From the astartectl documentation:
```
Claims can also be specified on a per-API set basis when requesting multiple API sets. Prefix a claim with "<api set>:" to apply
the specified claim only to the requested API set. For example:

	astartectl utils gen-jwt all-realm-apis -k test-realm.key -c appengine:GET::* -c pairing:POST::*

Would generate a token with only the desired claims for appengine and pairing.
```

Find [here](https://docs.astarte-platform.org/astarte/latest/070-auth.html#authorization) more information on possible claim values

2024-12-02 13:57 UTC, merged

2024-12-02 15:06 UTC, Jusuf95 commented
> Code is good! It would be great to add, in another PR, tests for the `-c` option. From the astartectl documentation:
> 
> ```
> Claims can also be specified on a per-API set basis when requesting multiple API sets. Prefix a claim with "<api set>:" to apply
> the specified claim only to the requested API set. For example:
> 
> 	astartectl utils gen-jwt all-realm-apis -k test-realm.key -c appengine:GET::* -c pairing:POST::*
> 
> Would generate a token with only the desired claims for appengine and pairing.
> ```
> 
> Find [here](https://docs.astarte-platform.org/astarte/latest/070-auth.html#authorization) more information on possible claim values

Thank you for your suggestion. I confirm that we will add tests for the -c option in the next PR, as per the documentation.