Add tests for JWT claim validation using astartectl
astarte-platform/astartectl_test_suite pull request #27
Opened 2024-12-06 12:52 UTC by Jusuf95

Add tests for verifying the claims in JWT tokens generated by astartectl for different claim types. 
The tests ensure that the claims are correctly displayed when the JWT is passed through the show-jwt-claims command.

Created tests for the following claim types:

- All Claims: Verifying that the claims a_aea, a_rma, a_pa, and a_ch appear in the output.
- AppEngine Claim (a_aea): Checking the presence of the a_aea claim in the JWT.
- Realm Management Claim (a_rma): Ensuring the presence of the a_rma claim.
- Pairing Claim (a_pa): Validating that the a_pa claim is included.
- Channels Claim (a_ch): Confirming the presence of the a_ch claim.

The tests generate JWTs for different roles and verify that the correct claims are displayed in the output of the astartectl utils show-jwt-claims command.

2024-12-06 14:03 UTC, osmanhadzic approved these changes

2024-12-06 15:30 UTC, Annopaolo requested changes

2024-12-06 15:30 UTC, Annopaolo commented on tests/utils/test_utils_show_jwt_claims.py
> +    except_output = ["a_aea", "a_rma", "a_pa", "a_ch"]
Nit: I would go with a name that's a little more clear, like:
```suggestion
    expected_output = ["a_aea", "a_rma", "a_pa", "a_ch"]
```

2024-12-06 15:31 UTC, Annopaolo commented on tests/utils/test_utils_show_jwt_claims.py
> +    except_output = ["a_aea", "a_rma", "a_pa", "a_ch"]
This suggestion applies to the other tests in this file too

2024-12-09 10:49 UTC, Annopaolo approved these changes

2024-12-09 10:49 UTC, merged