Refactor test file structure
astarte-platform/astartectl_test_suite pull request #8
Opened 2024-10-31 07:34 UTC by osmanhadzic

- Added a new folder structure and moved existing tests to the new folder structure.
- Added tests for getting sample data from Astarte.

The new folder structure was necessary to better organize the tests and improve maintainability. Additionally, the new tests were added to ensure that the app engine can correctly fetch sample data from Astarte.

Tests for server object parametric and nonparametric data streams were not added because the Astarte import does not support this type of interfaces.

2024-10-31 15:38 UTC, ackermannW requested changes

2024-10-31 15:38 UTC, ackermannW commented on tests/app_engine/device/app_engine_device_get_samples/test_app_engine_device_get_samples_default.py
> +        sample_data_result.stdout = [parse_element(el) for el in sample_data_result.stdout]
These three lines repeat through multiple tests. It would be wise to put them in a function.

2024-10-31 15:38 UTC, ackermannW commented on tests/app_engine/device/app_engine_device_get_samples/test_app_engine_device_get_samples_default.py
> +                parsed_elements_list.append(element.replace("]", ""))
These few lines repeat through multiple tests. It would be wise to put them in a function.

2024-11-05 08:38 UTC, ackermannW requested changes

2024-11-05 08:38 UTC, ackermannW commented on tests/app_engine/device/app_engine_device_get_samples/test_app_engine_device_get_samples_default.py
> +                list.append(element.replace("]", ""))
Here we can call `_extract_elements_from_brackets`.

2024-11-05 08:38 UTC, ackermannW commented on tests/app_engine/device/app_engine_device_get_samples/test_app_engine_device_get_samples_default.py
> +                list.append(element.replace("]", ""))
Here we can call `_extract_elements_from_brackets`.

2024-11-05 13:53 UTC, ackermannW approved these changes

2024-11-06 10:45 UTC, Annopaolo approved these changes

2024-11-06 10:46 UTC, merged